diccionario_marcas_modelos = {'volkswagen': ['golf', 'andere', 'passat', 'polo', 'scirocco', 'transporter', 'jetta', 'eos', 'touran', 'lupo', 'caddy', 'tiguan', 'sharan', 'up', 'fox', 'beetle', 'touareg', 'kaefer', 'phaeton', 'cc', 'bora', 'amarok'],
'audi': ['a8', 'a4', 'a1', 'tt', 'a6', '80', '100', 'a3', 'a2', 'a5', 'q5', '90', 'q3', 'q7', '200'],
'jeep': ['wrangler', 'cherokee', 'grand cherokee', 'renegade', 'compass'],
'skoda': ['superb', 'kodiaq', 'rapid', 'fabia', 'yeti', 'octavia', 'roomster', 'citigo'],
'bmw': ['116i', '118i', '120i', '125i', '130i', '135i', '218i', '220i', '225i', '316i', '318i', '320i', '325i', '328i', '335i', '418i', '420i', '428i', '435i', '520i', '523i', '528i', '535i', '550i', '640i', '650i', '730i', '740i', '750i', '760i', '840i', '850i', 'x1', 'x3', 'x5', 'z3', 'z4', 'i3', 'i8', 'm135i', 'm235i', 'm3', 'm4', 'm5', 'm6', 'x5_m', 'z4_m', 'x6_m'],
'peugeot': ['205', '305', '105', '405', '505', '805', '605', '607', '606', '608', '807', '808', '506', '507', '408', '106', '107', '108', '206', '207', '208', '306', '307', '308', '406', '407', '508', '806', '807', 'partner', 'expert', 'boxer'],
'ford': ['c_max', 'ka', 'fiesta', 'escort', 'focus', 'mustang', 'mondeo', 's_max', 'galaxy', 'transit', 'kuga', 'fusion', 'b_max'],
'mazda': ['mazda3', 'mazda6', 'mazda5', 'rx', 'mazda1', 'mx', 'cx_reihe', '323', '626', 'tribute'],
'nissan': ['altima', 'maxima', 'sentra', 'rogue', 'pathfinder', 'navara', 'micra', 'almera', 'primera', 'juke', 'qashqai', 'x_trail', 'note'],
'renault': ['kadjar', 'captur', 'twingo', 'clio', 'kangoo', 'scenic', 'megane', 'r19', 'espace', 'modus', 'andere', 'laguna'],
'mercedes_benz': ['g_230', 'g_240', 'g_250', 'g_270', 'g_280', 'g_290', 'g_300', 'g_320', 'g_350', 'g_400', 'g_500', 'g_55_amg', 'g_63_amg', 'g_65_amg', 's_250', 's_280', 's_300', 's_320', 's_350', 's_400', 's_420', 's_430', 's_500', 's_550', 's_600', 's_63_amg', 's_65_amg', 'e_200', 'e_220', 'e_230', 'e_240', 'e_250', 'e_260', 'e_270', 'e_280', 'e_300', 'e_320', 'e_350', 'e_400', 'e_500', 'e_550', 'e_63_amg', 'c_180', 'c_200', 'c_220', 'c_230', 'c_240', 'c_250', 'c_280', 'c_300', 'c_350', 'c_400', 'c_450', 'c_63_amg', 'b_150', 'b_160', 'b_170', 'b_180', 'b_200', 'b_220', 'b_250', 'a_140', 'a_160', 'a_170', 'a_180', 'a_200', 'a_220', 'a_250', 'a_45_amg', 'ml', 'vito', 'sprinter', 'slk', 'glk', 'viano', 'sl', 'clk', 'gl', '190'],
'opel': ['meriva', 'kadett', 'corsa', 'signum', 'astra', 'insignia', 'combo', 'omega', 'zafira', 'vectra', 'agila', 'tigra', 'calibra', 'antara', 'vivaro'],
'seat': ['arosa', 'ibiza', 'cordoba', 'mii', 'leon', 'exeo', 'alhambra', 'toledo', 'altea'],
'citroen': ['c4', 'berlingo', 'c1', 'c3', 'c5', 'c2'],
'honda': ['logo', 'prelude', 'integra', 'fr', 'insight', 's2000', 'city', 'stream', 'shuttle', 'civic', 'accord', 'cr', 'hr', 'jazz'],
'fiat': ['tipo', 'punto', 'panda', 'seicento', '500', 'stilo', 'ducato', 'bravo', 'croma', 'doblo'],
'mini': ['cooper', 'countryman', 'clubman', 'convertible', 'one'],
'smart': ['fortwo', 'forfour', 'roadster'],
'hyundai': ['lantra', 'trajet', 'galloper', 'i_10', 'i_20', 'i_30', 'i40', 'i40', 'matrix', 'atos', 'coupe', 'sonata', 'accent', 'elantra', 'terracan', 'i10', 'i20', 'i30', 'tucson', 'kona', 'getz', 'santa'],
'alfa_romeo': ['giulia', 'stelvio', 'giulietta', '156', '147', 'spider', '159', 'andere', '145'],
'subaru': ['impreza', 'forester', 'outback', 'xv', 'justy', 'legacy'],
'volvo': ['245', '945', '340', '760', '440', '460', '960', '340', '740', '430', '940', '240', '480', 's40', 's60', 's70', 's80', 's90', 'xc', 'v40', 'v50', 'v70', '850', 'v60', 'v90', 'c30', 'c70'],
'mitsubishi': ['asx', 'eclipse', 'l200', 'colt', 'carisma', 'galant', 'lancer', 'pajero', 'outlander'],
'kia': ['sportage', 'sorento', 'ceed', 'rio', 'picanto', 'carnival'],
'suzuki': ['swift', 'vitara', 's_cross', 'jimny', 'grand'],
'lancia': ['ypsilon', 'lybra', 'musa', 'delta', 'elefantino', 'kappa'],
'porsche': ['911', 'cayenne', 'macan', 'panamera', 'boxster'],
'toyota': ['avensis', 'corolla', 'verso', 'rav', 'yaris', 'aygo', 'auris', 'c_hr'],
'chevrolet': ['camaro', 'cruze', 'equinox', 'trax', 'matiz', 'spark', 'captiva', 'aveo', 'corvette'],
'dacia': ['sandero', 'duster', 'logan', 'lodgy'],
'daihatsu': ['sirion', 'terios', 'copen', 'cuore', 'charade', 'move', 'materia'],
'trabant': ['601', 'p601', 'tramp', 'p70'],
'saab': ['9_3', '9_5', '900', '9000'],
'chrysler': ['300c', 'voyager', 'grand_voyager', 'ptcruiser', 'crossfire', 'grand', 'voyager'],
'oldsmobile': ['alero', 'intrigue', 'bravada'],
'dodge': ['charger', 'challenger', 'durango', 'journey', 'caliber', 'ram'],
'jaguar': ['xf', 'xj', 'f_type', 'e_pace', 'x_type', 's_type'],
'daewoo': ['matiz', 'lanos', 'nubira', 'kalos'],
'rover': ['75', '45', '25'],
'lexus': ['is', 'es', 'nx', 'rx'],
'land_rover': ['discovery', 'range_rover', 'range_rover_sport', 'freelander', 'range_rover_evoque', 'defender', 'serie_2', 'serie_3', 'serie_1', 'discovery_sport'],
'abarth': ['500', '595', '124 spider'],
'mg': ['mg3', 'mg_zs', 'mg_hs', 'mg_zx', 'mg6', 'mg5', 'mg_sv', 'mg_zr', 'mg_zt', 'mg_tf', 'mga', 'mgb', 'mgc', 'mgf'],
'iveco': ['daily', 'eurocargo', 'stralis'],
'cadillac': ['ats', 'cts', 'escalade'],
'buick': ['regal', 'enclave', 'encore'],
'bentley': ['continental_gt', 'bentayga', 'mulsanne'],
'triumph': ['tr6', 'spitfire', 'stag'],
'ferrari': ['458', 'f12 berlinetta', 'laferrari'],
'lada': ['niva', 'granta', 'vesta', 'samara', 'kalina'],
'lotus': ['elise', 'evora', 'exige'],
'pontiac': ['firebird', 'gto', 'grand_prix'],
'proton': ['saga', 'persona', 'preve'],
'maserati': ['ghibli', 'quattroporte', 'levante'],
'isuzu': ['d-max', 'mu-x', 'trooper'],
'ssangyong': ['tivoli', 'korando', 'rexton', 'musso'],
'lincoln': ['navigator', 'aviator', 'continental'],
'infiniti': ['q50', 'q60', 'qx50', 'qx80'],
'lamborghini': ['aventador', 'huracan', 'urus'],
'rolls_royce': ['phantom', 'ghost', 'cullinan'],
'gmc': ['sierra', 'yukon', 'terrain'],
'uaz': ['hunter', 'patriot', 'bukhanka'],
'ligier': ['js50', 'js_50_l', 'js_50_sport'],
'morgan': ['plus_four', 'roadster', 'aero_8'],
'caterham': ['seven', '620r', 'super_seven'],
'tata': ['tiago', 'nexon', 'harrier'],
'aston_martin': ['vantage', 'db11', 'dbs_superleggera'],
'wiesmann': ['mf3', 'mf4', 'mf5'],
'tesla': ['model_3', 'model_s', 'model_x', 'model_y'],
'mclaren': ['570s', '720s', 'p1'],
'alpine': ['a110', 'a310', 'a610'],
'amc': ['amx', 'javelin', 'gremlin'],
'bugatti': ['chiron', 'veyron', 'divo'],
'mahindra': ['scorpio', 'xuv500', 'thar'],
'ktm': ['x_bow', 'rc_390', 'duke']}